service: sls-application

plugins: 
  - serverless-offline
  - serverless-plugin-typescript

provider: 
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-1
  stage: dev
  memorySize: 256
  timeout: 30

  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: '*'

        - Effect: Allow
          Action:
            - 's3:GetObject'
            - 's3:PutObject'
          Resource:
            - 'arn:aws:s3:::trancuongttlc-bucket/*'

functions: 
  api:  
    handler: ./index.appHandler
    timeout: 30
    memorySize: 1024
    events: 
      - httpApi: '*'

resources:
  Resources:
    MyS3Bucket: 
      Type: AWS::S3::Bucket
      Properties:
        BucketName: trancuongttlc-bucket