export enum ErrorMessageEnum {
  NOT_FOUND = "NOT FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  BAD_REQUEST = "BAD REQUEST",
  DOWNLOAD_ERROR = "DOWNLOAD ERROR",
}
